<a href="https://colab.research.google.com/github/miguelmorandini/am-t4-s1a2026/blob/main/aula2403_amt4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução a Python

In [ ]:
a=2
b=3
print('A soma é: ',a+b)

A soma é:  5

## Segunda Camada

In [ ]:
c=4
d=5
print('A multiplicação é: ',c*d)

A multiplicação é:  20

# Bibliotecas e Funções de Python

In [ ]:
import math

def equacao2grau(a, b, c):
  delta = b**2 - 4*a*c

  if(delta < 0):
    return 'Número sem raiz', delta

  x1 = (-b + math.sqrt(delta)) / (2*a)
  x2 = (-b - math.sqrt(delta)) / (2*a)

  return x1, x2

## Testes de Função Matemática

In [ ]:
eq = equacao2grau(1, -3, 2)
print(eq)

(2.0, 1.0)

In [ ]:
import random

for i in range(5):
  a = random.randint(-5, 1)
  b = random.randint(-10, 10)
  c = random.randint(-10, 10)

eq += equacao2grau(a, b, c)

print(eq[0])

2.0

In [ ]:
for i in range(12):
  if( i % 2 == 0):
    if(eq[i] != 'Número sem raiz'):
      print('X1: [',eq[i],']')
  else:
    if(eq[i] != 'Número sem raiz'):
      print('X2: [',eq[i],']\n')

X1: [ 2.0 ]
X2: [ 1.0 ]

X1: [ -1.0816659994661328 ]
X2: [ 3.0816659994661326 ]

X1: [ -3.1374586088176875 ]
X2: [ 0.6374586088176875 ]

X1: [ -1.098076211353316 ]
X2: [ 4.098076211353316 ]

X1: [ -1.3507810593582121 ]
X2: [ 1.8507810593582121 ]

X1: [ -3.0 ]
X2: [ 0.3333333333333333 ]

print(eq)

# Trabalhando com Dados Externos

## Bibliotecas de uso de pipeline

In [1]:
!pip -q install plotly        #instala biblioteca para gráficos interativos (zoom, hover, dashboards)
!pip -q install yellowbrick   #instala visualizações para modelos de ML (curvas, clusters, métricas)

In [4]:
import pandas as pd               #manipulação de dados (tabelas/DataFrame)
import numpy as np                #operações matemáticas e arrays
import seaborn as sns             #gráficos estatísticos mais simples
import matplotlib.pyplot as plt   #criação de gráficos básicos
import plotly.express as px       #gráficos interativos

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
base_credit = pd.read_csv('/content/drive/MyDrive/DSM/5º Semestre - 2026/aprendizagem-de-maquina/amt4/credit_data.csv')

In [8]:
base_credit

      clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

In [9]:
base_credit.describe()

          clientid        income          age          loan      default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [11]:
base_credit.head(10)

   clientid        income        age         loan  default
0         1  66155.925095  59.017015  8106.532131        0
1         2  34415.153966  48.117153  6564.745018        0
2         3  57317.170063  63.108049  8020.953296        0
3         4  42709.534201  45.751972  6103.642260        0
4         5  66952.688845  18.584336  8770.099235        1
5         6  24904.064140  57.471607    15.498598        0
6         7  48430.359613  26.809132  5722.581981        0
7         8  24500.141984  32.897548  2971.003310        1
8         9  40654.892537  55.496853  4755.825280        0
9        10  25075.872771  39.776378  1409.230371        0

In [12]:
base_credit.tail(10)

      clientid        income        age         loan  default
1990      1991  34237.575419  34.101654  2658.090632        0
1991      1992  26300.446554  45.539385  2317.393678        0
1992      1993  30803.806165  23.250084   623.024153        0
1993      1994  54421.410155  26.821928  3273.631823        0
1994      1995  24254.700791  37.751622  2225.284643        0
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

In [13]:
base_credit[base_credit['income'] > 69995.0]

     clientid        income        age         loan  default
422       423  69995.685578  52.719673  2084.370861        0

In [23]:
base_credit[base_credit['loan'] < 1.3777630]

     clientid        income        age     loan  default
865       866  28072.604355  54.142548  1.37763        0

# Analise e Anomalias Exploratórias

#Anáise de Anomalia Idade Negativa

In [24]:
base_credit.loc[base_credit['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0